### ISSUE TITLE
Support for Loire platform

### ISSUE THREAD

**Issue by jaylinski** [sonyxperiadev/kernel-sony-msm-4.14-common#8]
Hi! (me again)

I noticed that the Loire and Tone platform were removed from the build script in 475639f5c8d618c3fa7383eb4c14e8ff620af97c.

Can someone explain why? According to https://developer.sony.com/develop/open-devices/get-started/supported-devices-and-functionality/ the Loire platform should still get support for Kernel 4.14.

![kernel support](https://static.developer.sony.com/images/image/v6/s3/uploads/2017/10/KernelSupport_OpenDevices_201910.png)

:pray:

**Comment by MarijnS95** [comment]
@jaylinski Looks like that picture was made before 4.14 got fully integrated in AOSP. There are a couple hurdles preventing Loire and Tone from operating with this kernel on the binary side, which is why they will remain on 4.9 but _do_ receive Android 10.

With the increasing number of platforms and devices to maintain by a consistently small open-source community it becomes impossible to test and develop solutions to them all, especially when the culprit lies in incompatible closed-source blobs.

But not to worry; the less time we have to spend on these (IMO slightly useless) massive kernel migrations, the more time is left to continue bringing up devices on Mainline (the latest stable Linux kernel). No promises yet as there is still a _lot_ (and I do mean **a lot**) of work ahead, but progress will be continuing during the downtime in AOSP/SODP (kernel) maintenance.

**Comment by jaylinski** [comment]
@MarijnS95 Thanks for the quick and detailed info! I understand your decision.

I guess you saying ` but do receive Android 10` means that Android 10.0 is not yet ready for Loire?

Were will I be notified when Android 10.0 support for Loire is ready? Here? https://developer.sony.com/develop/open-devices/latest-updates

**Comment by MarijnS95** [comment]
> I guess you saying ` but do receive Android 10` means that Android 10.0 is not yet ready for Loire?

The branches/tags have been split off yesterday, and should already support it. All devices were initially brought up on Android 10 with kernel 4.9 after all.

I just have no idea if everything is still compatible and/or all tags are pointing to the right commits yet; mainly because I don't have the time to validate a build on-device. But if you have, by all means feel free to do so and report back. Keep in mind that you need to use the blobs for Android 9 when using kernel 4.9.

**Comment by jaylinski** [comment]
Thanks, I'll try it!
